project:
  type: website
  output-dir: docs

website:
  title: "Haley Daarstad"
  site-url: "https://haleydaarstad.com"
  description: "PhD Candidate in Political Science at UC Davis, studying criminal violence and gender."
  search: false
  navbar:
    title: "Haley Daarstad"
    collapse-below: lg
    right:
      - text: "research"
        href: papers.qmd
      - text: "teaching"
        href: teaching.qmd
      - text: "data"
        href: data.qmd
      - text: "gallery"
        href: gallery.qmd
  page-navigation: true
  back-to-top-navigation: false
  page-footer:
    left:
      - text: "© 2026 Haley Daarstad"
    center:
      - href: https://github.com/hbdaarstad
        icon: github
        aria-label: GitHub
      - href: mailto:hbdaarstad@ucdavis.edu
        icon: envelope
        aria-label: Email
    right:
      - text: "haleydaarstad.com"
        href: https://haleydaarstad.com
  google-analytics:
    tracking-id: "G-YEV9W8VPSW"

format:
  html:
    theme: [hd-custom.scss]
    toc: false
    grid:
      body-width: 800px

link-external-icon: false
link-external-newwindow: true

execute:
  freeze: auto
